version: '3'

volumes: 
  data:

networks: 
  database:
  web:

services: 
  db:
    image: postgres:13.1
    environment: 
      POSTGRES_PASSWORD: 1234
    volumes:
      # Volume dos dados
      - data:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - database
  
  frontend:
    image: nginx:1.19.6
    volumes: 
      # Website
      - ./web:/usr/share/nginx/html/
      # Configuração do Proxy Reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
    networks: 
      - web
    depends_on: 
      - app

  app:
    image: python:3.6
    volumes: 
      - ./app:/app
    working_dir: /app
    env_file: .env
    command: bash ./app.sh
    networks: 
     - database
     - web
    depends_on: 
      - db